name: Scheduled build

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: php
        run: echo "Hello World"
