name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
      - run: php -v
      - run: php -r "echo $_SERVER['DOCUMENT_ROOT'].PHP_EOL;"
      - run: php get_file.php