name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
      - run: php -v
      - run: echo $_SERVER['DOCUMENT_ROOT']
      - run: php get_file.php